def function():
    print()
    print('y')
    print('^       0')
    print('|      0')
    print('|     0')
    print('|    0')
    print('|   0')
    print('|  0')
    print('| 0')
    print('|0')
    print('0')
    print('|')
    print('|')
    print('|----------------------------> x')
